# Generated by Django 5.0.2 on 2024-02-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_subjects_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subgroup',
            field=models.IntegerField(default=0),
        ),
    ]
